version: 2
updates:
  # ルートのウェブサイトの依存関係をチェック
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "live"
    ignore:
      - dependency-name: "eslint"
    versioning-strategy: increase
    groups:
      angular:
        applies-to: version-updates
        patterns:
          - "tar"
        update-types:
          - "minor"
          - "patch"

  # CLI の依存関係をチェック
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "live"
    ignore:
      - dependency-name: "eslint"
    versioning-strategy: increase
    groups:
      angular:
        applies-to: version-updates
        patterns:
          - "tar"
        update-types:
          - "minor"
          - "patch"
  
  # テンプレート: with-i18n-routing の依存関係をチェック
  - package-ecosystem: "npm"
    directory: "/examples/app/with-i18n-routing"
    schedule:
      interval: "live"
    ignore:
      - dependency-name: "eslint"
    versioning-strategy: increase
    groups:
      angular:
        applies-to: version-updates
        patterns:
          - "tar"
        update-types:
          - "minor"
          - "patch"

  
  # テンプレート: without-i18n-routing の依存関係をチェック
  - package-ecosystem: "npm"
    directory: "/examples/app/without-i18n-routing"
    schedule:
      interval: "live"
    ignore:
      - dependency-name: "eslint"
    versioning-strategy: increase
    groups:
      angular:
        applies-to: version-updates
        patterns:
          - "tar"
        update-types:
          - "minor"
          - "patch"